name: Eficare.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }} 
    - run: | 
        cd client
        npm i 
        npm run build
        echo "Contents of client/build directory:"
        ls -la build/
        mv build/ ../server/static
        echo "Contents of server directory after moving build:"
        ls -la ../server/
        echo "Contents of server/static directory:"
        ls -la ../server/static
        npm install pm2 -g
        cd ..
        npm install
        echo "Stopping all PM2 processes (if any)..."
        pm2 stop all || echo "No PM2 processes were running."
        echo "Starting PM2 process..."
        pm2 start server.js --name eficare
        pm2 save
        sudo service nginx restart
