name: Eficare.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }} 
    - run: | 
        cd client
        npm i 
        npm run build
        ls -la build/
        mv build/ ../server/static
        ls -la ../server/
        npm install pm2 -g
        cd ../server
        npm i
        pm2 stop all
        pm2 start server.js --name eficare
        pm2 save
        sudo service nginx restart
